#include <fstream>
#include <iostream>
#include <sstream>
#include "lexer.h"
#include "parser.h"
#include "compiler.h"

int main(int argc, char* argv[]) {
    if (argc < 2) {
        std::cout << "Usage: ./meow <file.meow>\n";
        return 1;
    }

    std::ifstream file(argv[1]);
    if (!file) {
        std::cout << "Could not open file: " << argv[1] << "\n";
        return 1;
    }

    std::stringstream buffer;
    buffer << file.rdbuf();

    Lexer lexer(buffer.str());
    auto tokens = lexer.tokenize();

    Parser parser(tokens);
    auto ast = parser.parse();

    Compiler compiler;
    auto bytecode = compiler.compile(ast);

    std::cout << "Parsing completed successfully.\n";
    std::cout << "\nGenerated Bytecode:\n";

    for (size_t i = 0; i < bytecode.size(); ++i) {
        std::cout << i << " : " << static_cast<int>(bytecode[i].op)
                  << " " << bytecode[i].operand << "\n";
    }
    return 0;
}
